### ISSUE TITLE
Cannot display /darknet_ros/detection_image with rviz / rqt_image_view

### ISSUE THREAD

**Issue by oysteinvolden** [pushkalkatara/darknet_ros#4]
Hi, great work on the repo.

I'm trying to get it running and I'm quite close. However, when I run command: roslaunch darknet_ros yolo_v3.launch (after source devel/setup.bash and roscore) one can see that darknet is running and GPU is used (I guess GPU 0 used means that GPU is accessed and nvidia-smi confirms that). But it does not display some messages like "waiting for image" after the network is finish to run, only messages like "inside tracking", "consumder done", "started darknet thread" before it stops. And when I start rviz, I find /darknet_ros/detection_image in the list, but the screen shows nothing.

Some facts that may help:

- The darknet itself runs perfectly
- Have only downloaded yolov3.weights in correct folder and changed launch file to include yolov3 instead of yolov2-tiny and build it with catkin.
- The yolov3.cfg looks fine (have not touched it) and I use yolov3.yaml.
- I am able to access web camera via uvc_camera packet when I run: rosrun uvc_camera uvc_camera_node and display it via rqt_image_view / rviz under raw_image
- ros.yaml is not changed. Is there something I can change there to make it work?

Any suggestions to approach the problem?

![sc1](https://user-images.githubusercontent.com/22060387/54476100-90022800-47f9-11e9-8bc4-a5992f219cb8.png)

![sc2](https://user-images.githubusercontent.com/22060387/54476103-96909f80-47f9-11e9-85e0-89fde2c1241e.png)

**Comment by pushkalkatara** [comment]
Hi @oysteinvolden , try launching the camera using the [video_stream_opencv](http://wiki.ros.org/video_stream_opencv) package's launch file.

**Comment by oysteinvolden** [comment]
Thank you so much!
It worked when a launched with command: roslaunch video_stream_opencv camera.launch :dancer:

**Comment by pushkalkatara** [comment]
Cheers! :+1: Closing the issue as it got resolved.
